#!/bin/bash

function log_step(){
  echo $* >&2
}

function fail_gruntsource(){
  log_step "CARABINER FAILED"
  log_step "Could not install Gruntsource. Do you have npm installed and on the PATH?"
  exit 1
}

function install_grunt_source(){
  log_step "Installing Gruntsource" >&2
  npm install -g grunt-source || fail_gruntsource
}

function create_gruntsource_file(){
  log_step "Setting up Carabiner"
  curl https://raw.githubusercontent.com/dvmtn/carabiner/master/Gruntsource.json.example > Gruntsource.json
}

function run_gruntsource_init(){
  log_step "Initialising project"
  grunt-source init
}

function complete_message(){
  log_step "Setup complete!"
  log_step 'Run `grunt-source dev` to begin developing'
  log_step 'Have fun!'
}

function rename_project(){
  local project_name="$1"
  log_step "Setting project name to $project_name"
  sed -i.sed_backup -e "s/new-project/${project_name}/" $file \
    package.json \
    html/index.jade \
    html/partials/header.jade
  find . -name '*.sed_backup' | xargs rm
}

function main(){
  [[ `which grunt-source` ]] || install_grunt_source
  create_gruntsource_file
  run_gruntsource_init
  [[ -n "$1" ]] && rename_project "$1"
  complete_message
}

main $*
